# Create web hosts based on docker image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-project
spec:
  selector:
    matchLabels:
      app: udacity-devops-capstone-project
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devops-capstone-project
    spec:
      containers:
      - name: udacity-devops-capstone-project
        image: aitha/capstone-project
        imagePullPolicy: Always
        ports:
        - containerPort: 80
